version: '3'
services:
  web-service:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:80
    secrets:
      - mysql_password
    command: ["npx", "nodemon", "app.js", "-L"]
  mysql:
    image:  mysql:8.0.34
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: vitalcheck
      MYSQL_USER: user_vitalcheck
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
volumes:
  mysql_data:
secrets:
  mysql_root_password:
    file: ./.secrets/mysql_root_password.txt
  mysql_password:
    file: ./.secrets/mysql_password.txt